spring.application.name=tax-compliance-service

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/tax_compliance_db
spring.datasource.username=root
spring.datasource.password=Rajesh@#2003

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
